//
// Copyright 2002 (C) Greg Bingleman <byngl@hotmail.com>
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// Translation of pcgen.core.CustomData
// CustomData.dart
// Translated from pcgen/core/CustomData.java
// File I/O uses dart:io. PrerequisiteWriter and CampaignOutput are stubbed.

import 'dart:io';

import 'globals.dart';
import 'settings_handler.dart';
import 'equipment.dart';
import 'race.dart';
import 'pc_class.dart';
import 'deity.dart';
import 'domain.dart';
import 'ability.dart';
import 'ability_category.dart';
import 'language.dart';
import 'pc_template.dart';
import 'spell/spell.dart';
import 'campaign.dart';
import 'package:flutter_pcgen/src/cdom/base/constants.dart';
import 'package:flutter_pcgen/src/core/pcobject.dart';
import 'package:flutter_pcgen/src/cdom/enumeration/string_key.dart';

class CustomData {
  CustomData._();

  static const String _autoGenWarnLine1 =
      '#This file auto-generated by PCGen. Manual editing not recommended.';
  static const String _autoGenWarnLine2 =
      '#Ensure PCGen is not running before editing. Make backups as errors may result in data loss.';

  static bool _customItemsLoaded = false;

  // ---------------------------------------------------------------------------
  // Readers
  // ---------------------------------------------------------------------------

  /// Returns a BufferedReader (as an IOSink / File) for custom equipment, or null.
  static File? getCustomEquipmentReader() {
    final String path = customEquipmentFilePath();
    final File f = File(path);
    return f.existsSync() ? f : null;
  }

  // ---------------------------------------------------------------------------
  // File path helpers
  // ---------------------------------------------------------------------------

  static String customBioSetFilePath(bool usePath) =>
      _getCustomPath('BioSet', usePath);

  static String customClassFilePath(bool usePath) =>
      _getCustomPath('Classes', usePath);

  static String customDeityFilePath(bool usePath) =>
      _getCustomPath('Deities', usePath);

  static String customDomainFilePath(bool usePath) =>
      _getCustomPath('Domains', usePath);

  static String customAbilityFilePath(bool usePath) =>
      _getCustomPath('Abilities', usePath);

  static String customFeatFilePath(bool usePath) =>
      _getCustomPath('Feats', usePath);

  static String customLanguageFilePath(bool usePath) =>
      _getCustomPath('Languages', usePath);

  static String customPurchaseModeFilePath(bool usePath, String gmName) =>
      _getCustomPath('PointBuyMethods', usePath, gmName: gmName);

  static String customRaceFilePath(bool usePath) =>
      _getCustomPath('Races', usePath);

  static String customSkillFilePath(bool usePath) =>
      _getCustomPath('Skills', usePath);

  static String customSpellFilePath(bool usePath) =>
      _getCustomPath('Spells', usePath);

  static String customTemplateFilePath(bool usePath) =>
      _getCustomPath('Templates', usePath);

  // ---------------------------------------------------------------------------
  // Write custom files
  // ---------------------------------------------------------------------------

  static void writeCustomFiles() {
    _ensureCustomDirExists();
    writePurchaseModeConfiguration();

    if (!_customItemsLoaded) return;

    _writeCustomBioSet();
    _writeCustomClasses();
    _writeCustomDeities();
    _writeCustomDomains();
    _writeCustomAbilities();
    _writeCustomFeats();
    writeCustomItems();
    _writeCustomLanguages();
    _writeCustomRaces();
    _writeCustomSkills();
    _writeCustomSpells();
    _writeCustomTemplates();
    _writeCustomSources();
  }

  static void _ensureCustomDirExists() {
    final String dirPath = _customDirPath();
    final Directory dir = Directory(dirPath);
    if (!dir.existsSync()) {
      try {
        dir.createSync(recursive: true);
      } catch (e) {
        // log: Unable to create custom data directory '$dirPath': $e
      }
    }
  }

  static String _customDirPath() {
    // stub: PCGenSettings.getCustomDir()
    return '${Directory.current.path}${Platform.pathSeparator}custom'
        '${Platform.pathSeparator}${SettingsHandler.getGameAsProperty().getName()}';
  }

  static void writeCustomItems() {
    final String filePath = customEquipmentFilePath();
    if (!_customItemsLoaded && File(filePath).existsSync()) {
      // log: Custom items had not been loaded, so we won't save them this time.
      return;
    }

    _ensureCustomDirExists();

    try {
      final IOSink bw = File(filePath).openWrite(encoding: systemEncoding);
      _writeAutoGenHeader(bw);

      for (final Equipment aEq in Globals.getContext()
          .getReferenceContext()
          .getConstructedCDOMObjects(Equipment)) {
        if (aEq.isType(Constants.typeCustom) && !aEq.isType('AUTO_GEN')) {
          aEq.save(bw);
        }
      }
      bw.close();
    } catch (e) {
      // log: Error in writeCustomItems: $e
    }
  }

  static void writePurchaseModeConfiguration() {
    _ensureCustomDirExists();
    final String filePath = customPurchaseModeFilePath(
        true, SettingsHandler.getGameAsProperty().getName());

    try {
      final IOSink bw = File(filePath).openWrite(encoding: systemEncoding);
      final dynamic pbStatCosts =
          SettingsHandler.getGameAsProperty().getPointBuyStatCostMap();
      if (pbStatCosts == null) {
        bw.close();
        return;
      }

      bw.write('#\n');
      bw.write('$_autoGenWarnLine1\n');
      bw.write('$_autoGenWarnLine2\n');
      bw.write('#\n');
      bw.write('# Point-buy ability score costs\n');
      bw.write('#\n');

      if ((pbStatCosts as Map).isNotEmpty) {
        for (final entry in pbStatCosts.entries) {
          final dynamic pbc = entry.value;
          final StringBuffer sb = StringBuffer();
          sb.write('STAT:${entry.key}\t\tCOST:${pbc.getBuyCost()}');

          final int iCount = pbc.getPrerequisiteCount() as int;
          if (iCount != 0) {
            // stub: PrerequisiteWriter
            for (final dynamic prereq in pbc.getPrerequisiteList()) {
              sb.write('\t');
              // stub: prereqWriter.write(writer, prereq)
              sb.write('# prereq stub');
            }
          }
          bw.write('${sb.toString()}\n');
        }
      }

      bw.write('#\n');
      bw.write('# Point-buy methods\n');
      bw.write('#\n');

      for (final dynamic pbm in SettingsHandler.getGameAsProperty()
          .getModeContext()
          .getReferenceContext()
          .getConstructedCDOMObjects(dynamic)) {
        bw.write('METHOD:${pbm.getDisplayName()}\t\tPOINTS:${pbm.getPointFormula()}\n');
      }

      bw.close();
    } catch (e) {
      // log: Error in writePurchaseModeConfiguration: $e
    }
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static String _getCustomPath(String type, bool usePath, {String? gmName}) {
    final String resolvedGmName =
        gmName ?? SettingsHandler.getGameAsProperty().getName();
    String aString = '';
    if (usePath) {
      // stub: PCGenSettings.getCustomDir()
      aString = Directory.current.path;
      aString += '${Platform.pathSeparator}$resolvedGmName';
    }
    return '$aString${Platform.pathSeparator}custom$type.lst';
  }

  static String customEquipmentFilePath() => _getCustomPath('Equipment', true);

  static void _writeAutoGenHeader(IOSink bw) {
    bw.write('#\n');
    bw.write('$_autoGenWarnLine1\n');
    bw.write('$_autoGenWarnLine2\n');
    bw.write('#\n');
  }

  static void _writeCustomHeader(IOSink bw) {
    _writeAutoGenHeader(bw);
    bw.write('SOURCELONG:Custom\tSOURCESHORT:Custom\n');
  }

  static void _writeCustomBioSet() {
    final String filePath = customBioSetFilePath(true);
    try {
      final IOSink bw = File(filePath).openWrite(encoding: systemEncoding);
      _writeAutoGenHeader(bw);

      for (final Race race in Globals.getContext()
          .getReferenceContext()
          .getConstructedCDOMObjects(Race)) {
        if (race.isType(Constants.typeCustom)) {
          final String key = race.getKeyName();
          // stub: SettingsHandler.getGameAsProperty().getBioSet().getBaseRegionPCCText(key)
          bw.write('# bio set for $key\n');
        }
      }
      bw.write('\n');
      bw.close();
    } catch (e) {
      // log: Error in writeCustomBioSet: $e
    }
  }

  static void _writeCustomClasses() {
    _writeCustomPObjects(
        customClassFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(PCClass)
            .iterator);
  }

  static void _writeCustomDeities() {
    _writeCustomPObjects(
        customDeityFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(Deity)
            .iterator);
  }

  static void _writeCustomDomains() {
    _writeCustomPObjects(
        customDomainFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(Domain)
            .iterator);
  }

  static void _writeCustomAbilities() {
    for (final AbilityCategory ac
        in SettingsHandler.getGameAsProperty().getAllAbilityCategories()) {
      _writeCustomPObjects(
          customAbilityFilePath(true),
          Globals.getContext()
              .getReferenceContext()
              .getManufacturerId(ac)
              .getAllObjects()
              .iterator);
    }
  }

  static void _writeCustomFeats() {
    final File f = File(customFeatFilePath(true));
    if (f.existsSync()) {
      try {
        f.deleteSync();
      } catch (_) {}
    }
  }

  static void _writeCustomLanguages() {
    _writeCustomPObjects(
        customLanguageFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(Language)
            .iterator);
  }

  static void _writeCustomPObjects(String filename, Iterator<PObject> it) {
    try {
      final IOSink bw = File(filename).openWrite(encoding: systemEncoding);
      _writeCustomHeader(bw);
      while (it.moveNext()) {
        final PObject pobj = it.current;
        if (pobj.isType(Constants.typeCustom)) {
          bw.write('${pobj.getPCCText()}\n');
        }
      }
      bw.close();
    } catch (e) {
      // log: Error in writeCustomPObjects for $filename: $e
    }
  }

  static void _writeCustomRaces() {
    _writeCustomPObjects(
        customRaceFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(Race)
            .iterator);
  }

  static void _writeCustomSkills() {
    _writeCustomPObjects(
        customSkillFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(dynamic)
            .iterator); // stub: Skill.class
  }

  static void _writeCustomSources() {
    for (final Campaign c in Globals.getCampaignList()) {
      if ((c.getSafeString(StringKey.destination) as String? ?? '').isNotEmpty) {
        // stub: CampaignOutput.output(Globals.getContext(), c)
        // log: stub CampaignOutput for ${c.getKeyName()}
      }
    }
  }

  static void _writeCustomSpells() {
    final String filePath = customSpellFilePath(true);
    try {
      final IOSink bw = File(filePath).openWrite(encoding: systemEncoding);
      _writeCustomHeader(bw);
      for (final Spell spell in Globals.getContext()
          .getReferenceContext()
          .getConstructedCDOMObjects(Spell)) {
        if (spell.isType(Constants.typeCustom)) {
          bw.write('${spell.getPCCText()}\n');
        }
      }
      bw.close();
    } catch (e) {
      // log: Error in writeCustomSpells: $e
    }
  }

  static void _writeCustomTemplates() {
    _writeCustomPObjects(
        customTemplateFilePath(true),
        Globals.getContext()
            .getReferenceContext()
            .getConstructedCDOMObjects(PCTemplate)
            .iterator);
  }

  // ---------------------------------------------------------------------------
  // Public setters
  // ---------------------------------------------------------------------------

  static void setCustomItemsLoaded(bool loaded) {
    _customItemsLoaded = loaded;
  }
}
