// Translation of pcgen.gui2.tools.Icons

import 'package:flutter/material.dart';

/// Path prefix for all PCGen image assets.
const String _resourcePath = 'assets/images/';

/// Enumeration of every icon used in PCGen.
///
/// Each value carries the file extension of the icon on disk.  The full asset
/// path is `assets/images/<name><extension>`.
///
/// Use [assetPath] to obtain a path suitable for [Image.asset] or
/// [AssetImage], and [imageWidget] for a ready-made [Image] widget.
enum Icons {
  about16('.gif'),
  add16('.gif'),
  alert16('.gif'),
  alignBottom16('.gif'),
  alignCenter16('.gif'),
  alignJustifyHorizontal16('.gif'),
  alignJustifyVertical16('.gif'),
  alignLeft16('.gif'),
  alignRight16('.gif'),
  alignTop16('.gif'),
  bBack16('.gif'),
  bBack24('.gif'),
  back16('.gif'),
  bookmarks16('.gif'),
  buttonArrowUp('.png'),
  buttonArrowDown('.png'),
  checklist16('.gif'),
  close16('.gif'),
  closeAll16('.gif'),
  closeX9('.gif'),
  composeMail16('.gif'),
  contextualHelp16('.gif'),
  copy16('.gif'),
  customZoom16('.gif'),
  cut16('.gif'),
  dDown16('.gif'),
  dDown24('.gif'),
  defaultPortrait('.gif'),
  delete16('.gif'),
  down16('.gif'),
  edit16('.gif'),
  editZoom16('.gif'),
  export16('.gif'),
  fForward16('.gif'),
  fForward24('.gif'),
  find16('.gif'),
  findAgain16('.gif'),
  forward16('.gif'),
  help16('.gif'),
  history16('.gif'),
  import16('.gif'),
  information16('.gif'),
  mediaStop16('.gif'),
  new16('.gif'),
  newEnvelope('.gif'),
  newNPC16('.gif'),
  ok16('.gif'),
  open16('.gif'),
  pageSetup16('.gif'),
  paste16('.gif'),

  /// PCGen application icon (was RESOURCE_APP_ICON).
  pcGenApp('.png'),
  pcgenIcon('.gif'),
  preferences16('.gif'),
  preferencesHighlightBlue16('.gif'),
  print16('.gif'),
  printPreview16('.gif'),
  properties16('.gif'),
  redo16('.gif'),
  refresh16('.gif'),
  remove16('.gif'),
  removePreferences16('.gif'),
  removeZoom16('.gif'),
  replace16('.gif'),
  save16('.gif'),
  saveAll16('.gif'),
  saveAs16('.gif'),
  search16('.gif'),
  sendMail16('.gif'),
  splashPcgen('.gif'),
  splashPcgenAlpha('.png'),
  splashPcgenBeta('.png'),
  stop16('.gif'),
  tipOfTheDay16('.gif'),
  uUp16('.gif'),
  uUp24('.gif'),
  undo16('.gif'),
  up16('.gif'),
  xButtonClick('.gif'),
  xButtonRoll('.gif'),
  xButtonStat('.gif'),
  zoom16('.gif'),
  zoomHighlightBlue16('.gif'),
  zoomIn16('.gif'),
  zoomOut16('.gif'),
  stockBrokenImage('-16.png'),
  stockColor('-16.png'),
  stockCopy('-16.png'),
  stockCut('-16.png'),
  stockExport('-16.png'),
  stockInsertGraphic('-16.png'),
  stockInsertTable('-16.png'),
  stockListBulet('-16.png'),
  stockListEnum('-16.png'),
  stockNew('-16.png'),
  stockPaste('-16.png'),
  stockRevert('-16.png'),
  stockSave('-16.png'),
  stockSpellcheck('-16.png'),
  stockTextAlignCenter('-16.png'),
  stockTextAlignLeft('-16.png'),
  stockTextAlignRight('-16.png'),
  stockTextBold('-16.png'),
  stockTextItalic('-16.png'),
  stockTextUnderline('-16.png'),
  menuModeRgb('.png');

  const Icons(this.extension);

  /// File extension including the leading dot (e.g. `'.gif'`, `'.png'`).
  final String extension;

  /// The original Java enum name used as the file name stem.
  ///
  /// Because Dart enum names are camelCase we map them back to the original
  /// mixed-case stem expected by the asset file system.
  String get _stem {
    // Map the Dart camelCase name to the original Java enum name.
    const stems = <Icons, String>{
      Icons.about16: 'About16',
      Icons.add16: 'Add16',
      Icons.alert16: 'Alert16',
      Icons.alignBottom16: 'AlignBottom16',
      Icons.alignCenter16: 'AlignCenter16',
      Icons.alignJustifyHorizontal16: 'AlignJustifyHorizontal16',
      Icons.alignJustifyVertical16: 'AlignJustifyVertical16',
      Icons.alignLeft16: 'AlignLeft16',
      Icons.alignRight16: 'AlignRight16',
      Icons.alignTop16: 'AlignTop16',
      Icons.bBack16: 'BBack16',
      Icons.bBack24: 'BBack24',
      Icons.back16: 'Back16',
      Icons.bookmarks16: 'Bookmarks16',
      Icons.buttonArrowUp: 'button_arrow_up',
      Icons.buttonArrowDown: 'button_arrow_down',
      Icons.checklist16: 'Checklist16',
      Icons.close16: 'Close16',
      Icons.closeAll16: 'CloseAll16',
      Icons.closeX9: 'CloseX9',
      Icons.composeMail16: 'ComposeMail16',
      Icons.contextualHelp16: 'ContextualHelp16',
      Icons.copy16: 'Copy16',
      Icons.customZoom16: 'CustomZoom16',
      Icons.cut16: 'Cut16',
      Icons.dDown16: 'DDown16',
      Icons.dDown24: 'DDown24',
      Icons.defaultPortrait: 'DefaultPortrait',
      Icons.delete16: 'Delete16',
      Icons.down16: 'Down16',
      Icons.edit16: 'Edit16',
      Icons.editZoom16: 'EditZoom16',
      Icons.export16: 'Export16',
      Icons.fForward16: 'FForward16',
      Icons.fForward24: 'FForward24',
      Icons.find16: 'Find16',
      Icons.findAgain16: 'FindAgain16',
      Icons.forward16: 'Forward16',
      Icons.help16: 'Help16',
      Icons.history16: 'History16',
      Icons.import16: 'Import16',
      Icons.information16: 'Information16',
      Icons.mediaStop16: 'MediaStop16',
      Icons.new16: 'New16',
      Icons.newEnvelope: 'NewEnvelope',
      Icons.newNPC16: 'NewNPC16',
      Icons.ok16: 'Ok16',
      Icons.open16: 'Open16',
      Icons.pageSetup16: 'PageSetup16',
      Icons.paste16: 'Paste16',
      Icons.pcGenApp: 'PCGenApp',
      Icons.pcgenIcon: 'PcgenIcon',
      Icons.preferences16: 'Preferences16',
      Icons.preferencesHighlightBlue16: 'PreferencesHighlightBlue16',
      Icons.print16: 'Print16',
      Icons.printPreview16: 'PrintPreview16',
      Icons.properties16: 'Properties16',
      Icons.redo16: 'Redo16',
      Icons.refresh16: 'Refresh16',
      Icons.remove16: 'Remove16',
      Icons.removePreferences16: 'RemovePreferences16',
      Icons.removeZoom16: 'RemoveZoom16',
      Icons.replace16: 'Replace16',
      Icons.save16: 'Save16',
      Icons.saveAll16: 'SaveAll16',
      Icons.saveAs16: 'SaveAs16',
      Icons.search16: 'Search16',
      Icons.sendMail16: 'SendMail16',
      Icons.splashPcgen: 'SplashPcgen',
      Icons.splashPcgenAlpha: 'SplashPcgen_Alpha',
      Icons.splashPcgenBeta: 'SplashPcgen_Beta',
      Icons.stop16: 'Stop16',
      Icons.tipOfTheDay16: 'TipOfTheDay16',
      Icons.uUp16: 'UUp16',
      Icons.uUp24: 'UUp24',
      Icons.undo16: 'Undo16',
      Icons.up16: 'Up16',
      Icons.xButtonClick: 'XButton_Click',
      Icons.xButtonRoll: 'XButton_Roll',
      Icons.xButtonStat: 'XButton_Stat',
      Icons.zoom16: 'Zoom16',
      Icons.zoomHighlightBlue16: 'ZoomHighlightBlue16',
      Icons.zoomIn16: 'ZoomIn16',
      Icons.zoomOut16: 'ZoomOut16',
      Icons.stockBrokenImage: 'stock_broken_image',
      Icons.stockColor: 'stock_color',
      Icons.stockCopy: 'stock_copy',
      Icons.stockCut: 'stock_cut',
      Icons.stockExport: 'stock_export',
      Icons.stockInsertGraphic: 'stock_insert_graphic',
      Icons.stockInsertTable: 'stock_insert_table',
      Icons.stockListBulet: 'stock_list_bulet',
      Icons.stockListEnum: 'stock_list_enum',
      Icons.stockNew: 'stock_new',
      Icons.stockPaste: 'stock_paste',
      Icons.stockRevert: 'stock_revert',
      Icons.stockSave: 'stock_save',
      Icons.stockSpellcheck: 'stock_spellcheck',
      Icons.stockTextAlignCenter: 'stock_text_align_center',
      Icons.stockTextAlignLeft: 'stock_text_align_left',
      Icons.stockTextAlignRight: 'stock_text_align_right',
      Icons.stockTextBold: 'stock_text_bold',
      Icons.stockTextItalic: 'stock_text_italic',
      Icons.stockTextUnderline: 'stock_text_underline',
      Icons.menuModeRgb: 'menu_mode_rgb',
    };
    return stems[this] ?? name;
  }

  /// The full Flutter asset path for this icon.
  String get assetPath => '$_resourcePath$_stem$extension';

  /// A ready-made [Image] widget for this icon.
  ///
  /// [size] sets both width and height; leave null to use the image's natural
  /// dimensions.
  Image imageWidget({double? size, BoxFit fit = BoxFit.contain}) {
    return Image.asset(assetPath, width: size, height: size, fit: fit);
  }

  /// An [ImageProvider] for this icon, usable with [DecorationImage] etc.
  ImageProvider get imageProvider => AssetImage(assetPath);
}
